#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleApp.Droid.Resource", IsApplication=true)]

namespace SampleApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::SampleApp.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::SampleApp.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int p10 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int p11 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int p12 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int p13 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int p14 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int p2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int p3 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int p4 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int p5 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int p6 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int p7 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int p8 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int p9 = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
